/**
 * Generated by "@vuepress/internal-root-mixins"
 */
import m0 from "C:\\workspace_web\\blog\\node_modules\\@vuepress\\core\\lib\\client\\root-mixins\\updateMeta.js"
import m1 from "C:\\workspace_web\\blog\\node_modules\\vuepress-plugin-nprogress\\lib\\clientRootMixin.js"
import m2 from "C:\\workspace_web\\blog\\node_modules\\vuepress-plugin-zooming\\lib\\clientRootMixin.js"

export default [
  m0,
  m1,
  m2
]