/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\workspace_web\\blog\\lib\\layouts\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-87d81770",
    path: "/posts/2020/09/01/algorithm.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-87d81770").then(next)
    },
  },
  {
    path: "/_posts/2020-09-01-algorithm.html",
    redirect: "/posts/2020/09/01/algorithm.html"
  },
  {
    name: "v-c4d70f70",
    path: "/posts/2020/09/12/algorithm.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-c4d70f70").then(next)
    },
  },
  {
    path: "/_posts/2020-09-12-algorithm.html",
    redirect: "/posts/2020/09/12/algorithm.html"
  },
  {
    name: "v-4f1d7112",
    path: "/custom-pages/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("CustomPages", "v-4f1d7112").then(next)
    },
  },
  {
    path: "/custom-pages/index.html",
    redirect: "/custom-pages/"
  },
  {
    name: "v-63bda530",
    path: "/posts/2020/11/12/algorithm.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Post", "v-63bda530").then(next)
    },
  },
  {
    path: "/_posts/2020-11-12-algorithm.html",
    redirect: "/posts/2020/11/12/algorithm.html"
  },
  {
    name: "v-b2754d56",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Home", "v-b2754d56").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-1f814451",
    path: "/posts/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Posts", "v-1f814451").then(next)
    },
  },
  {
    path: "/posts/index.html",
    redirect: "/posts/"
  },
  {
    name: "v-03721585",
    path: "/posts/tags/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-03721585").then(next)
    },
  },
  {
    path: "/posts/tags/index.html",
    redirect: "/posts/tags/"
  },
  {
    name: "v-5eb9e6bc",
    path: "/posts/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Categories", "v-5eb9e6bc").then(next)
    },
  },
  {
    path: "/posts/categories/index.html",
    redirect: "/posts/categories/"
  },
  {
    name: "v-15a28c69",
    path: "/posts/tags/알고리즘.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-15a28c69").then(next)
    },
    meta: {"tagName":"알고리즘"}
  },
  {
    name: "v-75676de2",
    path: "/posts/tags/정렬.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-75676de2").then(next)
    },
    meta: {"tagName":"정렬"}
  },
  {
    name: "v-02a62250",
    path: "/posts/tags/python.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-02a62250").then(next)
    },
    meta: {"tagName":"python"}
  },
  {
    name: "v-74cf165b",
    path: "/posts/tags/C++.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-74cf165b").then(next)
    },
    meta: {"tagName":"C++"}
  },
  {
    name: "v-5e3a42ec",
    path: "/posts/categories/algorithm.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-5e3a42ec").then(next)
    },
    meta: {"categoryName":"algorithm"}
  },
  {
    path: '*',
    component: GlobalLayout
  }
]