/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "duckback45",
  "description": "Vuepress theme of meteorlxy's blog",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "버블정렬",
      "frontmatter": {
        "top": 1,
        "category": "algorithm",
        "tags": [
          "알고리즘",
          "정렬",
          "python"
        ],
        "date": "2020-09-01T00:00:00.000Z",
        "title": "버블정렬",
        "vssue": false,
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false
      },
      "regularPath": "/_posts/2020-09-01-algorithm.html",
      "relativePath": "_posts/2020-09-01-algorithm.md",
      "key": "v-87d81770",
      "path": "/posts/2020/09/01/algorithm.html",
      "headers": [
        {
          "level": 2,
          "title": "python",
          "slug": "python"
        }
      ],
      "type": "post",
      "top": 1,
      "tags": [
        "알고리즘",
        "정렬",
        "python"
      ],
      "category": "algorithm",
      "createdAt": "2020-09-01",
      "updatedAt": null
    },
    {
      "title": "다항식의 덧셈",
      "frontmatter": {
        "top": 1,
        "category": "algorithm",
        "tags": [
          "알고리즘",
          "C++"
        ],
        "date": "2020-09-12T00:00:00.000Z",
        "title": "다항식의 덧셈",
        "vssue": false,
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false
      },
      "regularPath": "/_posts/2020-09-12-algorithm.html",
      "relativePath": "_posts/2020-09-12-algorithm.md",
      "key": "v-c4d70f70",
      "path": "/posts/2020/09/12/algorithm.html",
      "headers": [
        {
          "level": 2,
          "title": "C++",
          "slug": "c"
        }
      ],
      "type": "post",
      "top": 1,
      "tags": [
        "알고리즘",
        "C++"
      ],
      "category": "algorithm",
      "createdAt": "2020-09-12",
      "updatedAt": null
    },
    {
      "title": "Reference - Custom Pages",
      "frontmatter": {
        "layout": "CustomPages",
        "title": "Reference - Custom Pages",
        "aside": false
      },
      "regularPath": "/custom-pages/",
      "relativePath": "custom-pages/index.md",
      "key": "v-4f1d7112",
      "path": "/custom-pages/",
      "headers": [
        {
          "level": 2,
          "title": "Add more pages",
          "slug": "add-more-pages"
        },
        {
          "level": 2,
          "title": "Custom Layout",
          "slug": "custom-layout"
        }
      ],
      "type": "page"
    },
    {
      "title": "병합정렬",
      "frontmatter": {
        "top": 2,
        "category": "algorithm",
        "tags": [
          "알고리즘",
          "정렬",
          "python"
        ],
        "date": "2020-11-12T00:00:00.000Z",
        "title": "병합정렬",
        "vssue": false,
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false
      },
      "regularPath": "/_posts/2020-11-12-algorithm.html",
      "relativePath": "_posts/2020-11-12-algorithm.md",
      "key": "v-63bda530",
      "path": "/posts/2020/11/12/algorithm.html",
      "headers": [
        {
          "level": 2,
          "title": "python",
          "slug": "python"
        }
      ],
      "type": "post",
      "top": 2,
      "tags": [
        "알고리즘",
        "정렬",
        "python"
      ],
      "category": "algorithm",
      "createdAt": "2020-11-12",
      "updatedAt": null
    },
    {
      "frontmatter": {
        "title": "Home",
        "layout": "Home"
      },
      "regularPath": "/",
      "key": "v-b2754d56",
      "path": "/",
      "type": "page"
    },
    {
      "frontmatter": {
        "title": "Posts",
        "layout": "Posts"
      },
      "regularPath": "/posts/",
      "key": "v-1f814451",
      "path": "/posts/",
      "type": "page"
    },
    {
      "frontmatter": {
        "title": "Tags",
        "layout": "Tags"
      },
      "regularPath": "/posts/tags/",
      "key": "v-03721585",
      "path": "/posts/tags/"
    },
    {
      "frontmatter": {
        "title": "Categories",
        "layout": "Categories"
      },
      "regularPath": "/posts/categories/",
      "key": "v-5eb9e6bc",
      "path": "/posts/categories/"
    },
    {
      "frontmatter": {
        "title": "알고리즘 | Tag",
        "layout": "Tag"
      },
      "regularPath": "/posts/tags/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98.html",
      "key": "v-15a28c69",
      "path": "/posts/tags/알고리즘.html"
    },
    {
      "frontmatter": {
        "title": "정렬 | Tag",
        "layout": "Tag"
      },
      "regularPath": "/posts/tags/%EC%A0%95%EB%A0%AC.html",
      "key": "v-75676de2",
      "path": "/posts/tags/정렬.html"
    },
    {
      "frontmatter": {
        "title": "python | Tag",
        "layout": "Tag"
      },
      "regularPath": "/posts/tags/python.html",
      "key": "v-02a62250",
      "path": "/posts/tags/python.html"
    },
    {
      "frontmatter": {
        "title": "C++ | Tag",
        "layout": "Tag"
      },
      "regularPath": "/posts/tags/C++.html",
      "key": "v-74cf165b",
      "path": "/posts/tags/C++.html"
    },
    {
      "frontmatter": {
        "title": "algorithm | Category",
        "layout": "Category"
      },
      "regularPath": "/posts/categories/algorithm.html",
      "key": "v-5e3a42ec",
      "path": "/posts/categories/algorithm.html"
    }
  ],
  "themeConfig": {
    "lang": {
      "home": "Home",
      "posts": "Posts",
      "category": "Category",
      "categories": "Categories",
      "tag": "Tag",
      "tags": "Tags",
      "allCategories": "All",
      "search": "Search",
      "searchHint": "Search in title and excerpt",
      "noRelatedPosts": "No related posts",
      "top": "Top",
      "createdAt": "Created",
      "updatedAt": "Updated",
      "prevPost": "Previous Post",
      "nextPost": "Next Post",
      "toc": "Table of Contents",
      "comments": "Comments",
      "notFound": "Oops ! The page is not here"
    },
    "personalInfo": {
      "nickname": "Baek Sanghun",
      "description": "   ",
      "email": "duckback45@gmail.com",
      "avatar": "/assets/img/1599481511381.jpg",
      "sns": {
        "github": {
          "account": "duckback45",
          "link": "https://github.com/duckback45"
        },
        "reddit": {
          "account": "duckback45",
          "link": "https://www.reddit.com/"
        }
      }
    },
    "header": {
      "background": {
        "useGeo": true
      },
      "showTitle": true
    },
    "footer": {
      "poweredBy": true,
      "poweredByTheme": true,
      "custom": "Copyright 2018-present meteorlxy | MIT License"
    },
    "infoCard": {
      "headerBackground": {
        "useGeo": true
      }
    },
    "lastUpdated": true,
    "nav": [
      {
        "text": "Home",
        "link": "/",
        "exact": true
      },
      {
        "text": "Posts",
        "link": "/posts/",
        "exact": false
      },
      {
        "text": "Github",
        "link": "https://github.com/duckback45"
      }
    ],
    "smoothScroll": false,
    "zooming": {},
    "comments": {
      "owner": "duck45",
      "repo": "vuepress-theme-meteorlxy",
      "clientId": "cbda894952ba70c00666",
      "clientSecret": "1ade785ca693bf3092be5e5338720d5ee43672b7",
      "autoCreateIssue": false
    },
    "pagination": {
      "perPage": 5
    },
    "prevPost": "Previous Post",
    "nextPost": "Next Post",
    "defaultPages": {}
  },
  "locales": {
    "/": {
      "lang": "en-US",
      "path": "/"
    }
  }
}