/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "duckback45",
  "description": "",
  "base": "/blog/",
  "headTags": [],
  "pages": [
    {
      "title": "버블정렬",
      "frontmatter": {
        "top": 4,
        "category": "algorithm",
        "tags": [
          "알고리즘",
          "정렬",
          "python"
        ],
        "date": "2020-09-01T00:00:00.000Z",
        "title": "버블정렬",
        "vssue": false,
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false
      },
      "regularPath": "/_posts/2020-09-01-bubble_sort.html",
      "relativePath": "_posts/2020-09-01-bubble_sort.md",
      "key": "v-23dbf20a",
      "path": "/posts/2020/09/01/bubble-sort.html",
      "headers": [
        {
          "level": 2,
          "title": "python",
          "slug": "python"
        }
      ],
      "lastUpdated": "6/18/2021, 4:44:07 PM",
      "lastUpdatedTimestamp": 1624002247000,
      "type": "post",
      "top": 4,
      "tags": [
        "알고리즘",
        "정렬",
        "python"
      ],
      "category": "algorithm",
      "createdAt": "2020-09-01",
      "updatedAt": "2021-06-18"
    },
    {
      "title": "다항식의 덧셈",
      "frontmatter": {
        "top": 5,
        "category": "algorithm",
        "tags": [
          "알고리즘",
          "C++"
        ],
        "date": "2020-09-12T00:00:00.000Z",
        "title": "다항식의 덧셈",
        "vssue": false,
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false
      },
      "regularPath": "/_posts/2020-09-12-cpp.html",
      "relativePath": "_posts/2020-09-12-cpp.md",
      "key": "v-2c4f688a",
      "path": "/posts/2020/09/12/cpp.html",
      "headers": [
        {
          "level": 2,
          "title": "C++",
          "slug": "c"
        }
      ],
      "lastUpdated": "6/18/2021, 4:44:07 PM",
      "lastUpdatedTimestamp": 1624002247000,
      "type": "post",
      "top": 5,
      "tags": [
        "알고리즘",
        "C++"
      ],
      "category": "algorithm",
      "createdAt": "2020-09-12",
      "updatedAt": "2021-06-18"
    },
    {
      "title": "병합정렬",
      "frontmatter": {
        "top": 3,
        "category": "algorithm",
        "tags": [
          "알고리즘",
          "정렬",
          "python"
        ],
        "date": "2020-11-12T00:00:00.000Z",
        "title": "병합정렬",
        "vssue": false,
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false
      },
      "regularPath": "/_posts/2020-11-12-merge_sort.html",
      "relativePath": "_posts/2020-11-12-merge_sort.md",
      "key": "v-1a4957da",
      "path": "/posts/2020/11/12/merge-sort.html",
      "headers": [
        {
          "level": 2,
          "title": "python",
          "slug": "python"
        }
      ],
      "lastUpdated": "6/18/2021, 4:44:07 PM",
      "lastUpdatedTimestamp": 1624002247000,
      "type": "post",
      "top": 3,
      "tags": [
        "알고리즘",
        "정렬",
        "python"
      ],
      "category": "algorithm",
      "createdAt": "2020-11-12",
      "updatedAt": "2021-06-18"
    },
    {
      "title": "퀵정렬",
      "frontmatter": {
        "top": 2,
        "category": "algorithm",
        "tags": [
          "알고리즘",
          "정렬",
          "python"
        ],
        "date": "2020-11-12T00:00:00.000Z",
        "title": "퀵정렬",
        "vssue": false,
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false
      },
      "regularPath": "/_posts/2020-11-11-quick_sort.html",
      "relativePath": "_posts/2020-11-11-quick_sort.md",
      "key": "v-757e0efb",
      "path": "/posts/2020/11/12/quick-sort.html",
      "headers": [
        {
          "level": 2,
          "title": "python",
          "slug": "python"
        }
      ],
      "lastUpdated": "6/18/2021, 4:44:07 PM",
      "lastUpdatedTimestamp": 1624002247000,
      "type": "post",
      "top": 2,
      "tags": [
        "알고리즘",
        "정렬",
        "python"
      ],
      "category": "algorithm",
      "createdAt": "2020-11-12",
      "updatedAt": "2021-06-18"
    },
    {
      "title": "01타일(acmicpc 1904)",
      "frontmatter": {
        "top": 1,
        "category": "algorithm",
        "tags": [
          "acmicpc",
          "알고리즘",
          "동적프로그래밍"
        ],
        "date": "2021-01-28T00:00:00.000Z",
        "title": "01타일(acmicpc 1904)",
        "vssue": false,
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false
      },
      "regularPath": "/_posts/2021-01-28-acmicpc_1904.html",
      "relativePath": "_posts/2021-01-28-acmicpc_1904.md",
      "key": "v-5332537e",
      "path": "/posts/2021/01/28/acmicpc-1904.html",
      "headers": [
        {
          "level": 2,
          "title": "소스코드 Python",
          "slug": "소스코드-python"
        }
      ],
      "lastUpdated": "6/18/2021, 4:44:07 PM",
      "lastUpdatedTimestamp": 1624002247000,
      "type": "post",
      "top": 1,
      "tags": [
        "acmicpc",
        "알고리즘",
        "동적프로그래밍"
      ],
      "category": "algorithm",
      "createdAt": "2021-01-28",
      "updatedAt": "2021-06-18"
    },
    {
      "title": "Z(acmicpc 1074)",
      "frontmatter": {
        "top": 1,
        "category": "algorithm",
        "tags": [
          "acmicpc",
          "알고리즘",
          "재귀"
        ],
        "date": "2021-01-19T00:00:00.000Z",
        "title": "Z(acmicpc 1074)",
        "vssue": false,
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false
      },
      "regularPath": "/_posts/2021-01-19-acmicpc_1074.html",
      "relativePath": "_posts/2021-01-19-acmicpc_1074.md",
      "key": "v-de7c2336",
      "path": "/posts/2021/01/19/acmicpc-1074.html",
      "headers": [
        {
          "level": 2,
          "title": "소스코드 Python",
          "slug": "소스코드-python"
        }
      ],
      "lastUpdated": "6/18/2021, 4:44:07 PM",
      "lastUpdatedTimestamp": 1624002247000,
      "type": "post",
      "top": 1,
      "tags": [
        "acmicpc",
        "알고리즘",
        "재귀"
      ],
      "category": "algorithm",
      "createdAt": "2021-01-19",
      "updatedAt": "2021-06-18"
    },
    {
      "title": "평범한 배낭(acmicpc 12865)",
      "frontmatter": {
        "top": 1,
        "category": "algorithm",
        "tags": [
          "acmicpc",
          "알고리즘",
          "동적프로그래밍"
        ],
        "date": "2021-01-28T00:00:00.000Z",
        "title": "평범한 배낭(acmicpc 12865)",
        "vssue": false,
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false
      },
      "regularPath": "/_posts/2021-01-28-acmicpc_12865.html",
      "relativePath": "_posts/2021-01-28-acmicpc_12865.md",
      "key": "v-776cc73b",
      "path": "/posts/2021/01/28/acmicpc-12865.html",
      "headers": [
        {
          "level": 2,
          "title": "소스코드 Python",
          "slug": "소스코드-python"
        }
      ],
      "lastUpdated": "8/26/2023, 12:28:45 AM",
      "lastUpdatedTimestamp": 1692977325000,
      "type": "post",
      "top": 1,
      "tags": [
        "acmicpc",
        "알고리즘",
        "동적프로그래밍"
      ],
      "category": "algorithm",
      "createdAt": "2021-01-28",
      "updatedAt": "2023-08-26"
    },
    {
      "title": "Reference - Custom Pages",
      "frontmatter": {
        "layout": "CustomPages",
        "title": "Reference - Custom Pages",
        "aside": false
      },
      "regularPath": "/custom-pages/",
      "relativePath": "custom-pages/index.md",
      "key": "v-0d59f3aa",
      "path": "/custom-pages/",
      "headers": [
        {
          "level": 2,
          "title": "Add more pages",
          "slug": "add-more-pages"
        },
        {
          "level": 2,
          "title": "Custom Layout",
          "slug": "custom-layout"
        }
      ],
      "lastUpdated": "11/12/2020, 4:09:00 AM",
      "lastUpdatedTimestamp": 1605121740000,
      "type": "page"
    },
    {
      "title": "소수 찾기",
      "frontmatter": {
        "top": 1,
        "category": "algorithm",
        "tags": [
          "프로그래머스",
          "완전탐색",
          "python"
        ],
        "date": "2021-02-18T00:00:00.000Z",
        "title": "소수 찾기",
        "vssue": false,
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false
      },
      "regularPath": "/_posts/2021-02-18-programmers-prime.html",
      "relativePath": "_posts/2021-02-18-programmers-prime.md",
      "key": "v-2f313a8a",
      "path": "/posts/2021/02/18/programmers-prime.html",
      "headers": [
        {
          "level": 2,
          "title": "python",
          "slug": "python"
        }
      ],
      "lastUpdated": "6/18/2021, 4:44:07 PM",
      "lastUpdatedTimestamp": 1624002247000,
      "type": "post",
      "top": 1,
      "tags": [
        "프로그래머스",
        "완전탐색",
        "python"
      ],
      "category": "algorithm",
      "createdAt": "2021-02-18",
      "updatedAt": "2021-06-18"
    },
    {
      "title": "행렬(1080)",
      "frontmatter": {
        "top": 1,
        "category": "greedy",
        "tags": [
          "greedy"
        ],
        "date": "2023-08-26T00:00:00.000Z",
        "title": "행렬(1080)",
        "vssue": false,
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false
      },
      "regularPath": "/_posts/2023-08-26-greedy.html",
      "relativePath": "_posts/2023-08-26-greedy.md",
      "key": "v-348774ce",
      "path": "/posts/2023/08/26/greedy.html",
      "headers": [
        {
          "level": 2,
          "title": "행렬 1080",
          "slug": "행렬-1080"
        },
        {
          "level": 3,
          "title": "분석",
          "slug": "분석"
        },
        {
          "level": 3,
          "title": "소스코드 Python",
          "slug": "소스코드-python"
        }
      ],
      "lastUpdated": "8/26/2023, 2:35:21 AM",
      "lastUpdatedTimestamp": 1692984921000,
      "type": "post",
      "top": 1,
      "tags": [
        "greedy"
      ],
      "category": "greedy",
      "createdAt": "2023-08-26",
      "updatedAt": "2023-08-26"
    },
    {
      "title": "공유기 설치(acmicpc 2110)",
      "frontmatter": {
        "top": 1,
        "category": "algorithm",
        "tags": [
          "acmicpc",
          "알고리즘",
          "이진탐색"
        ],
        "date": "2021-01-22T00:00:00.000Z",
        "title": "공유기 설치(acmicpc 2110)",
        "vssue": false,
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false
      },
      "regularPath": "/_posts/2021-01-22-acmicpc_2110.html",
      "relativePath": "_posts/2021-01-22-acmicpc_2110.md",
      "key": "v-129670d1",
      "path": "/posts/2021/01/22/acmicpc-2110.html",
      "headers": [
        {
          "level": 2,
          "title": "소스코드 Python",
          "slug": "소스코드-python"
        }
      ],
      "lastUpdated": "6/18/2021, 4:44:07 PM",
      "lastUpdatedTimestamp": 1624002247000,
      "type": "post",
      "top": 1,
      "tags": [
        "acmicpc",
        "알고리즘",
        "이진탐색"
      ],
      "category": "algorithm",
      "createdAt": "2021-01-22",
      "updatedAt": "2021-06-18"
    },
    {
      "title": "주사위(1041)",
      "frontmatter": {
        "top": 1,
        "category": "greedy",
        "tags": [
          "greedy",
          "수학"
        ],
        "date": "2023-08-28T00:00:00.000Z",
        "title": "주사위(1041)",
        "vssue": false,
        "layout": "Post",
        "permalink": "/posts/:year/:month/:day/:slug.html",
        "draft": false
      },
      "regularPath": "/_posts/2023-08-28-dice.html",
      "relativePath": "_posts/2023-08-28-dice.md",
      "key": "v-8e723862",
      "path": "/posts/2023/08/28/dice.html",
      "headers": [
        {
          "level": 2,
          "title": "주사위 1041",
          "slug": "주사위-1041"
        },
        {
          "level": 3,
          "title": "분석",
          "slug": "분석"
        },
        {
          "level": 3,
          "title": "소스코드 Python",
          "slug": "소스코드-python"
        }
      ],
      "type": "post",
      "top": 1,
      "tags": [
        "greedy",
        "수학"
      ],
      "category": "greedy",
      "createdAt": "2023-08-28",
      "updatedAt": null
    },
    {
      "frontmatter": {
        "title": "Home",
        "layout": "Home"
      },
      "regularPath": "/",
      "key": "v-b2754d56",
      "path": "/",
      "type": "page"
    },
    {
      "frontmatter": {
        "title": "Posts",
        "layout": "Posts"
      },
      "regularPath": "/posts/",
      "key": "v-1f814451",
      "path": "/posts/",
      "type": "page"
    },
    {
      "frontmatter": {
        "title": "Tags",
        "layout": "Tags"
      },
      "regularPath": "/posts/tags/",
      "key": "v-03721585",
      "path": "/posts/tags/"
    },
    {
      "frontmatter": {
        "title": "Categories",
        "layout": "Categories"
      },
      "regularPath": "/posts/categories/",
      "key": "v-5eb9e6bc",
      "path": "/posts/categories/"
    },
    {
      "frontmatter": {
        "title": "알고리즘 | Tag",
        "layout": "Tag"
      },
      "regularPath": "/posts/tags/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98.html",
      "key": "v-15a28c69",
      "path": "/posts/tags/알고리즘.html"
    },
    {
      "frontmatter": {
        "title": "정렬 | Tag",
        "layout": "Tag"
      },
      "regularPath": "/posts/tags/%EC%A0%95%EB%A0%AC.html",
      "key": "v-75676de2",
      "path": "/posts/tags/정렬.html"
    },
    {
      "frontmatter": {
        "title": "python | Tag",
        "layout": "Tag"
      },
      "regularPath": "/posts/tags/python.html",
      "key": "v-02a62250",
      "path": "/posts/tags/python.html"
    },
    {
      "frontmatter": {
        "title": "C++ | Tag",
        "layout": "Tag"
      },
      "regularPath": "/posts/tags/C++.html",
      "key": "v-74cf165b",
      "path": "/posts/tags/C++.html"
    },
    {
      "frontmatter": {
        "title": "acmicpc | Tag",
        "layout": "Tag"
      },
      "regularPath": "/posts/tags/acmicpc.html",
      "key": "v-609bbe46",
      "path": "/posts/tags/acmicpc.html"
    },
    {
      "frontmatter": {
        "title": "동적프로그래밍 | Tag",
        "layout": "Tag"
      },
      "regularPath": "/posts/tags/%EB%8F%99%EC%A0%81%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%B0%8D.html",
      "key": "v-3fe657a1",
      "path": "/posts/tags/동적프로그래밍.html"
    },
    {
      "frontmatter": {
        "title": "재귀 | Tag",
        "layout": "Tag"
      },
      "regularPath": "/posts/tags/%EC%9E%AC%EA%B7%80.html",
      "key": "v-6c7231c9",
      "path": "/posts/tags/재귀.html"
    },
    {
      "frontmatter": {
        "title": "프로그래머스 | Tag",
        "layout": "Tag"
      },
      "regularPath": "/posts/tags/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4.html",
      "key": "v-10797bde",
      "path": "/posts/tags/프로그래머스.html"
    },
    {
      "frontmatter": {
        "title": "완전탐색 | Tag",
        "layout": "Tag"
      },
      "regularPath": "/posts/tags/%EC%99%84%EC%A0%84%ED%83%90%EC%83%89.html",
      "key": "v-f011318c",
      "path": "/posts/tags/완전탐색.html"
    },
    {
      "frontmatter": {
        "title": "greedy | Tag",
        "layout": "Tag"
      },
      "regularPath": "/posts/tags/greedy.html",
      "key": "v-0c496cd8",
      "path": "/posts/tags/greedy.html"
    },
    {
      "frontmatter": {
        "title": "이진탐색 | Tag",
        "layout": "Tag"
      },
      "regularPath": "/posts/tags/%EC%9D%B4%EC%A7%84%ED%83%90%EC%83%89.html",
      "key": "v-7b23f1cc",
      "path": "/posts/tags/이진탐색.html"
    },
    {
      "frontmatter": {
        "title": "수학 | Tag",
        "layout": "Tag"
      },
      "regularPath": "/posts/tags/%EC%88%98%ED%95%99.html",
      "key": "v-569bc58e",
      "path": "/posts/tags/수학.html"
    },
    {
      "frontmatter": {
        "title": "algorithm | Category",
        "layout": "Category"
      },
      "regularPath": "/posts/categories/algorithm.html",
      "key": "v-5e3a42ec",
      "path": "/posts/categories/algorithm.html"
    },
    {
      "frontmatter": {
        "title": "greedy | Category",
        "layout": "Category"
      },
      "regularPath": "/posts/categories/greedy.html",
      "key": "v-5459ae57",
      "path": "/posts/categories/greedy.html"
    }
  ],
  "themeConfig": {
    "lang": {
      "home": "Home",
      "posts": "Posts",
      "category": "Category",
      "categories": "Categories",
      "tag": "Tag",
      "tags": "Tags",
      "allCategories": "All",
      "search": "Search",
      "searchHint": "Search in title and excerpt",
      "noRelatedPosts": "No related posts",
      "top": "Top",
      "createdAt": "Created",
      "updatedAt": "Updated",
      "prevPost": "Previous Post",
      "nextPost": "Next Post",
      "toc": "Table of Contents",
      "comments": "Comments",
      "notFound": "Oops ! The page is not here"
    },
    "personalInfo": {
      "nickname": "Baek Sanghun",
      "description": "   ",
      "email": "duckback45@gmail.com",
      "avatar": "./assets/img/1599481511381.jpg",
      "sns": {
        "github": {
          "account": "duckback45",
          "link": "https://github.com/duckback45"
        },
        "reddit": {
          "account": "duckback45",
          "link": "https://www.reddit.com/"
        }
      }
    },
    "header": {
      "background": {
        "useGeo": true
      },
      "showTitle": true
    },
    "footer": {
      "poweredBy": true,
      "poweredByTheme": true,
      "custom": "Copyright 2018-present meteorlxy | MIT License"
    },
    "infoCard": {
      "headerBackground": {
        "useGeo": true
      }
    },
    "lastUpdated": true,
    "nav": [
      {
        "text": "Home",
        "link": "/",
        "exact": true
      },
      {
        "text": "Posts",
        "link": "/posts/",
        "exact": false
      },
      {
        "text": "Github",
        "link": "https://github.com/duckback45"
      }
    ],
    "smoothScroll": false,
    "zooming": {},
    "pagination": {
      "perPage": 5
    },
    "prevPost": "Previous Post",
    "nextPost": "Next Post",
    "defaultPages": {},
    "comments": {}
  },
  "locales": {
    "/": {
      "lang": "en-US",
      "path": "/"
    }
  }
}