/**
 * Generated by "@vuepress/plugin-blog (meteorlxy modified version)"
 */
export default {
  "algorithm": {
    "path": "/posts/categories/algorithm.html",
    "pageKeys": [
      "v-23dbf20a",
      "v-2c4f688a",
      "v-1a4957da",
      "v-757e0efb",
      "v-5332537e",
      "v-de7c2336",
      "v-776cc73b",
      "v-2f313a8a",
      "v-129670d1"
    ]
  },
  "greedy": {
    "path": "/posts/categories/greedy.html",
    "pageKeys": [
      "v-348774ce",
      "v-8e723862"
    ]
  }
}